version: '2'
services:
### ---- mysql containers ----
  mysql8:
    container_name: mysql
    build:
      context: ./mock/mysql/
    ports:
      - "3306:3306"
#      - "33060:33060" # X API
    volumes:
      - ./mock/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: hoge123
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    platform: linux/amd64 # M1 Macの場合

  graphql-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    depends_on:
      - mysql8
### ---- mysql containers ----


volumes:
#  react-node-modules:
#  react-node-modules-relay:
  react-node-modules-mysql: