// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID      string `json:"id"`
	User    *User  `json:"user"`
	Message string `json:"message"`
}

type NewMessage struct {
	Message string `json:"message"`
	UserID  string `json:"userID"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
